config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.featured_content.body
    - field.field.node.featured_content.field_fc_weight
    - field.field.node.featured_content.field_slideshow_image
    - image.style.thumbnail
    - node.type.featured_content
  module:
    - content_moderation
    - image_widget_crop
    - imce
    - text
id: node.featured_content.default
targetEntityType: node
bundle: featured_content
mode: default
content:
  body:
    weight: 2
    type: text_textarea_with_summary
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
    third_party_settings: {  }
    region: content
  field_fc_weight:
    type: number
    weight: 3
    region: content
    settings:
      placeholder: ''
    third_party_settings: {  }
  field_slideshow_image:
    weight: 1
    type: image_widget_crop
    settings:
      show_default_crop: true
      preview_image_style: thumbnail
      crop_preview_image_style: crop_thumbnail
      progress_indicator: throbber
      crop_list:
        - '4_3'
      show_crop_area: false
      warn_multiple_usages: false
    third_party_settings:
      imce:
        enabled: false
    region: content
  moderation_state:
    type: moderation_state_default
    weight: 4
    settings: {  }
    region: content
    third_party_settings: {  }
  title:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
hidden:
  created: true
  langcode: true
  path: true
  promote: true
  status: true
  sticky: true
  uid: true
  url_redirects: true
