config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.profile_showcase.body
    - field.field.node.profile_showcase.field_body_headline
    - field.field.node.profile_showcase.field_display_text
    - field.field.node.profile_showcase.field_image_profile
    - field.field.node.profile_showcase.field_satelllite_profiles
    - image.style.thumbnail
    - node.type.profile_showcase
  module:
    - content_moderation
    - image_widget_crop
    - imce
    - path
    - text
id: node.profile_showcase.default
targetEntityType: node
bundle: profile_showcase
mode: default
content:
  body:
    weight: 4
    type: text_textarea_with_summary
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
    third_party_settings: {  }
    region: content
  created:
    type: datetime_timestamp
    weight: 10
    region: content
    settings: {  }
    third_party_settings: {  }
  field_body_headline:
    weight: 3
    type: text_textfield
    settings:
      size: 80
      placeholder: ''
    third_party_settings: {  }
    region: content
  field_display_text:
    weight: 1
    type: text_textfield
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
  field_image_profile:
    weight: 2
    type: image_widget_crop
    settings:
      show_default_crop: true
      preview_image_style: thumbnail
      crop_preview_image_style: crop_thumbnail
      progress_indicator: throbber
      crop_list:
        - square
      show_crop_area: false
      warn_multiple_usages: false
    third_party_settings:
      imce:
        enabled: false
    region: content
  field_satelllite_profiles:
    weight: 5
    type: options_buttons
    settings: {  }
    third_party_settings: {  }
    region: content
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  moderation_state:
    type: moderation_state_default
    weight: 100
    settings: {  }
    region: content
    third_party_settings: {  }
  path:
    type: path
    weight: 30
    region: content
    settings: {  }
    third_party_settings: {  }
  promote:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 15
    region: content
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 121
    third_party_settings: {  }
    region: content
  sticky:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 16
    region: content
    third_party_settings: {  }
  title:
    type: string_textfield
    weight: -5
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 5
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    region: content
    third_party_settings: {  }
hidden: {  }
