config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.news.body
    - field.field.node.news.field_news_image
    - field.field.node.news.field_release_date
    - field.field.node.news.field_send_to_bsos
    - image.style.thumbnail
    - node.type.news
  module:
    - content_moderation
    - datetime
    - image_widget_crop
    - imce
    - path
    - text
id: node.news.default
targetEntityType: node
bundle: news
mode: default
content:
  body:
    weight: 2
    type: text_textarea_with_summary
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
    third_party_settings: {  }
    region: content
  created:
    type: datetime_timestamp
    weight: 8
    region: content
    settings: {  }
    third_party_settings: {  }
  field_news_image:
    weight: 1
    type: image_widget_crop
    settings:
      show_default_crop: true
      preview_image_style: thumbnail
      crop_preview_image_style: crop_thumbnail
      crop_list:
        - square
      progress_indicator: throbber
      show_crop_area: false
      warn_multiple_usages: false
    third_party_settings:
      imce:
        enabled: false
    region: content
  field_release_date:
    weight: 3
    type: datetime_default
    settings: {  }
    third_party_settings: {  }
    region: content
  field_send_to_bsos:
    weight: 4
    type: options_buttons
    settings: {  }
    third_party_settings: {  }
    region: content
  moderation_state:
    weight: 5
    settings: {  }
    third_party_settings: {  }
    type: moderation_state_default
    region: content
  path:
    type: path
    weight: 9
    region: content
    settings: {  }
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 6
    region: content
    third_party_settings: {  }
  title:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 7
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    region: content
    third_party_settings: {  }
  url_redirects:
    weight: 10
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  langcode: true
  promote: true
  sticky: true
