config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.dept_items_of_interest.field_dept_item_link
    - field.field.node.dept_items_of_interest.field_dept_item_weight
    - node.type.dept_items_of_interest
  module:
    - link
    - user
id: node.dept_items_of_interest.default
targetEntityType: node
bundle: dept_items_of_interest
mode: default
content:
  field_dept_item_link:
    label: above
    weight: 0
    type: link
    settings:
      trim_length: 80
      url_only: false
      url_plain: false
      rel: ''
      target: ''
    third_party_settings: {  }
    region: content
  field_dept_item_weight:
    label: above
    weight: 1
    type: number_integer
    settings:
      thousand_separator: ''
      prefix_suffix: true
    third_party_settings: {  }
    region: content
hidden:
  langcode: true
  links: true
