config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.links_to_us.field_social_icon
    - field.field.node.links_to_us.field_sort_order
    - field.field.node.links_to_us.field_url
    - node.type.links_to_us
  module:
    - options
    - user
id: node.links_to_us.default
targetEntityType: node
bundle: links_to_us
mode: default
content:
  field_social_icon:
    label: above
    weight: 1
    type: list_default
    settings: {  }
    third_party_settings: {  }
    region: content
  field_sort_order:
    label: above
    weight: 2
    type: number_integer
    settings:
      thousand_separator: ''
      prefix_suffix: true
    third_party_settings: {  }
    region: content
  field_url:
    label: above
    weight: 0
    type: string
    settings:
      link_to_entity: false
    third_party_settings: {  }
    region: content
hidden:
  langcode: true
  links: true
