config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.landing_topic.body
    - field.field.node.landing_topic.field_imagelanding
    - field.field.node.landing_topic.field_landingtopic_order
    - field.field.node.landing_topic.field_links_landing
    - field.field.node.landing_topic.taxonomy_vocabulary_2
    - image.style.500w
    - node.type.landing_topic
  module:
    - ds
    - fences
    - field_group
    - image
    - link
    - text
    - user
third_party_settings:
  field_group:
    group_row:
      children:
        - group_main
        - group_secondary
      parent_name: ''
      weight: 0
      format_type: html_element
      format_settings:
        id: ''
        classes: row
        element: div
        show_label: false
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
      label: Row
      region: content
    group_main:
      children:
        - body
        - field_links_landing
      parent_name: group_row
      weight: 1
      format_type: html_element
      format_settings:
        id: ''
        classes: col-md-8
        element: div
        show_label: false
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
      label: Main
      region: content
    group_secondary:
      children:
        - field_imagelanding
      parent_name: group_row
      weight: 2
      format_type: html_element
      format_settings:
        id: ''
        classes: col-md-4
        element: div
        show_label: false
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
      label: Secondary
      region: content
id: node.landing_topic.default
targetEntityType: node
bundle: landing_topic
mode: default
content:
  body:
    label: hidden
    type: text_default
    weight: 1
    settings: {  }
    third_party_settings: {  }
    region: content
  field_imagelanding:
    label: hidden
    weight: 3
    type: image
    settings:
      image_style: 500w
      image_link: ''
    third_party_settings:
      fences:
        fences_field_tag: div
        fences_field_classes: ''
        fences_field_item_tag: div
        fences_field_item_classes: ''
        fences_label_tag: div
        fences_label_classes: ''
      ds:
        ft:
          id: default
          settings:
            lb: ''
            lb-col: false
            classes: {  }
    region: content
  field_links_landing:
    type: link
    weight: 2
    region: content
    label: hidden
    settings:
      trim_length: null
      url_only: false
      url_plain: false
      rel: '0'
      target: '0'
    third_party_settings:
      fences:
        fences_field_tag: div
        fences_field_classes: ''
        fences_field_item_tag: div
        fences_field_item_classes: ''
        fences_label_tag: div
        fences_label_classes: ''
      ds:
        ds_limit: ''
        ft:
          id: default
          settings:
            lb: ''
            lb-col: false
            classes: {  }
hidden:
  field_landingtopic_order: true
  langcode: true
  links: true
  taxonomy_vocabulary_2: true
