_core:
  default_config_hash: Pw2ELXqyW0bEUY_MdnD9pok5eWjoA2FutauHW4wzHbQ
position: center
vertical: 0
horizontal: 10
fixed: 1
width: 400px
autoclose: 0
opendelay: 0.5
disable_autoclose: 0
show_countdown: 1
hover_autoclose: 1
popin:
  effect: slideDown
  duration: slow
popout:
  effect: fadeIn
  duration: slow
jquery_ui:
  draggable: 1
  resizable: 0
visibility:
  message_type:
    id: message_type
    negate: false
    context_mapping:
      better_messages: '@better_messages.context:better_messages'
    message_types: {  }
  node_type:
    id: node_type
    negate: false
    context_mapping:
      node: '@node.node_route_context:node'
    bundles: {  }
  request_path:
    id: request_path
    negate: false
    pages: ''
  user_role:
    id: user_role
    negate: false
    context_mapping:
      user: '@user.current_user_context:current_user'
    roles: {  }
  'entity_bundle:node':
    id: 'entity_bundle:node'
    negate: false
    context_mapping:
      node: '@node.node_route_context:node'
    bundles: {  }
  'entity_bundle:taxonomy_term':
    id: 'entity_bundle:taxonomy_term'
    negate: false
    context_mapping:
      taxonomy_term: '@taxonomy_term.taxonomy_term_route_context:taxonomy_term'
    bundles: {  }
