abs_urls: false
admin_theme: false
roles_profiles:
  faculty_member:
    public: member
  staff:
    public: member
  graduate_student:
    public: member
  project_creator:
    public: superuser_profile
  project_editor:
    public: superuser_profile
  publication_creator:
    public: superuser_profile
  publication_editor:
    public: superuser_profile
  area_about_us_contributing_editor:
    public: superuser_profile
  area_graduate_contributing_editor:
    public: superuser_profile
  area_news_events_contributing_editor:
    public: superuser_profile
  area_about_us_editor:
    public: superuser_profile
  area_graduate_editor:
    public: superuser_profile
  area_faculty_staff_editor:
    public: superuser_profile
  area_alumni_giving_editor:
    public: superuser_profile
  area_academics_research_editor:
    public: superuser_profile
  area_news_events_editor:
    public: superuser_profile
  area_diversity_editor:
    public: superuser_profile
  profile_showcase_contributing_editor:
    public: superuser_profile
  profile_showcase_editor:
    public: superuser_profile
  items_of_interest_editor:
    public: superuser_profile
  news_creator:
    public: superuser_profile
  news_contributing_editor:
    public: superuser_profile
  news_editor:
    public: superuser_profile
  events_editor:
    public: superuser_profile
  user_profile_editor:
    public: superuser_profile
  user_editor:
    public: superuser_profile
  department_web_editor:
    public: dwe_super_user_profile
  administrator:
    public: admin
    private: admin
_core:
  default_config_hash: 4FhrEwOM9yJ8neEoN77sxroTRBUXqRwap0KSJtFnYJs
