umd_schoolwide_header:
  embed: '<script src="https://umd-header.umd.edu/build/bundle.js?search=0&search_domain=&events=0&news=0&schools=0&admissions=0&support=0&support_url=&wrapper=&sticky=0"></script>'
